#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "biboumi"
name = "Biboumi"
description.en = "XMPP gateway for the IRC network"
description.fr = "Passerelle XMPP pour le réseau IRC"

version = "9.0~ynh1"

maintainers = ["pitchum"]

[upstream]
license = "Zlib"
website = "https://biboumi.louiz.org"
admindoc = "https://doc.biboumi.louiz.org"
code = "https://github.com/louiz/biboumi"

[integration]
yunohost = ">= 12.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

[resources]

    [resources.ports]
    main.default = 113

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    dir = "/var/lib/__APP__"

    [resources.permissions]

    [resources.apt]
    packages = [ "biboumi", ]
