#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    preinstall = """
        yunohost app install prosody --args 'domain=domain.tld&import_from_metronome=0' --force
    """
