#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
admin=$YNH_APP_ARG_ADMIN

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

if dpkg --compare-versions "$(uname -r)" "<=" "4.0"
then
    ynh_die "Upgrade your kernel first. Unsupported version: $(uname -r)"
fi

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=admin --value=$admin

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression --message="Finding an available port..." --weight=2

# Find a free port
port=$(ynh_find_port --port=113)
ynh_app_setting_set --app=$app --key=port --value=$port

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=9

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# SPECIFIC SETUP
#=================================================
# CONFIGURE BIBOUMI
#=================================================

# Create a secret password that will be shared by metronome and biboumi.
secret="$(ynh_string_random 25)"
# Biboumi needs at least one admin JID.
admin_jid="${admin}@biboumi.${domain}"
biboumi_config_file="/etc/biboumi/biboumi.cfg"

ynh_add_config --template="../conf/biboumi.cfg" --destination="/etc/biboumi/biboumi.cfg"

#=================================================
# CONFIGURE METRONOME
#=================================================

# Add metronome component
ynh_add_config --template="../conf/biboumi.cfg.lua" --destination="/etc/metronome/conf.d/biboumi.cfg.lua"

#=================================================
# CREATE DIRECTORIES
#=================================================

mkdir -p /var/log/biboumi /var/lib/biboumi

# Set permissions to app files
chown _biboumi /var/log/biboumi /var/lib/biboumi /etc/biboumi

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

# Use logrotate to manage application logfile(s)
ynh_use_logrotate /var/log/biboumi/

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add biboumi --description="XMPP gateway for the IRC network" --log="/var/log/biboumi/biboumi.log"

#=================================================
# SET THE APP AS NOT USING THE SSO
#=================================================

# Prevent conflict with other apps on the same domain
ynh_app_setting_set --app=$app --key=no_sso --value=1

#=================================================
# RELOAD SERVICES
#=================================================

ynh_systemd_action --action=restart --service_name=metronome
ynh_systemd_action --action=restart --service_name=biboumi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of Biboumi completed" --last
