#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

if dpkg --compare-versions "$(uname -r)" "<=" "4.0"; then
    ynh_die "Upgrade your kernel first. Unsupported version: $(uname -r)"
fi

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

shared_secret="$(ynh_string_random --length=25)"
ynh_app_setting_set --key="shared_secret" --value="$shared_secret"

admin_jid="${admin}@${app}.${domain}"
ynh_app_setting_set --key="admin_jid" --value="$admin_jid"

#=================================================
# CREATE DATA DIRECTORY
#=================================================
ynh_script_progression "Setting up the data directory..."

# Set permissions to app files
chown -R _biboumi:_biboumi "/var/lib/$app"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

# Stop the service started by apt install
ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

# Add metronome component
metronome_config_dir=$(_get_metronome_config_dir)
ynh_config_add --template="metronome.cfg.lua" --destination="$metronome_config_dir/$app.cfg.lua"
chown metronome:metronome "$metronome_config_dir/$app.cfg.lua"
ynh_systemctl --service="metronome" --action="restart"

# Add biboumi configuration
mkdir -p "/etc/$app/"
ynh_config_add --template="biboumi.cfg" --destination="/etc/$app/$app.cfg"
chown -R _biboumi:_biboumi "/etc/$app/$app.cfg"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="XMPP gateway for the IRC network" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R _biboumi:_biboumi "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="Authenticated with the XMPP server"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
