#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status | grep -q $app
then
	echo "Remove $app service"
	yunohost service remove $app
fi

#=================================================
# REMOVE DEPENDENCIES
#=================================================

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove the app directory securely
ynh_secure_remove "/etc/biboumi"
ynh_secure_remove "/var/lib/biboumi"

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE LOGS
#=================================================

ynh_secure_remove "/var/log/biboumi"

#=================================================
# REMOVE BACKPORTS LIST
#=================================================

ynh_secure_remove "/etc/apt/sources.list.d/${app}_needs_stretch-backports.list"

#=================================================
# REMOVE METRONOME COMPONENT
#=================================================

ynh_secure_remove "/etc/metronome/conf.d/biboumi.cfg.lua"
