#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
	yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_systemctl --service="$app" --action="stop" --log_path="systemd"
systemctl disable "$app.service" --quiet

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove data directory
ynh_safe_rm "/var/lib/$app"

# Remove a directory securely
ynh_safe_rm "/etc/$app"

# Remove Metronome component
ynh_safe_rm "$(_get_metronome_config_dir)/$app.cfg.lua"
ynh_systemctl --action=restart --service=metronome

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
