#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DETECT XMPP SERVER SOFTWARE IN USE
#=================================================

xmpp_app=$(_get_xmpp_app_name)
config_filename=$(_get_xmpp_server_config_filename $xmpp_app)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
	yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_systemd_action --service_name="$app" --action="stop" --log_path="systemd"
systemctl disable "$app.service" --quiet

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..."

# Remove data directory
ynh_secure_remove --file="/var/lib/$app"

# Remove a directory securely
ynh_secure_remove --file="/etc/$app"

# Remove Metronome component
ynh_secure_remove --file="$config_filename"
ynh_systemd_action --action=restart --service_name=$xmpp_app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
