#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================
ynh_script_progression "Validating restoration parameters..."

if dpkg --compare-versions "$(uname -r)" "<=" "4.0"; then
    ynh_die "Upgrade your kernel first. Unsupported version: $(uname -r)"
fi

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "/var/lib/$app"
chown -R _biboumi:_biboumi "/var/lib/$app"

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/etc/$app"
chown -R _biboumi:_biboumi "/etc/$app"

metronome_config_dir=$(_get_metronome_config_dir)
ynh_restore "$metronome_config_dir/$app.cfg.lua"
chown metronome:metronome "$metronome_config_dir/$app.cfg.lua"
ynh_systemctl --service=metronome --action="restart"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="XMPP gateway for the IRC network" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/var/log/$app/"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R _biboumi:_biboumi "/var/log/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Authenticated with the XMPP server"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
