#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================
ynh_script_progression --message="Validating restoration parameters..." --weight=1

if dpkg --compare-versions "$(uname -r)" "<=" "4.0"
then
    ynh_die "Upgrade your kernel first. Unsupported version: $(uname -r)"
fi

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Reinstalling dependencies..." --weight=9

# Make sure that stretch-backports is enabled
ynh_install_app_dependencies $pkg_dependencies

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================

ynh_restore_file --origin_path="/etc/biboumi"
ynh_restore_file --origin_path="/var/lib/biboumi"

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add biboumi --description="XMPP gateway for the IRC network" --log="/var/log/biboumi/biboumi.log"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================

mkdir -p /var/log/biboumi
ynh_restore_file --origin_path="/etc/logrotate.d/$app"

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chown _biboumi /var/log/biboumi /var/lib/biboumi /etc/biboumi

#=================================================
# RESTORE THE METRONOME CONFIG
#=================================================

ynh_restore_file --origin_path="/etc/metronome/conf.d/biboumi.cfg.lua"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD SERVICES
#=================================================

ynh_systemd_action --action=restart --service_name=metronome
ynh_systemd_action --action=restart --service_name=biboumi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
