#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
admin=$(ynh_app_setting_get $app admin)
port=$(ynh_app_setting_get $app port)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

# Prevent conflict with other apps on the same domain
ynh_app_setting_set $app no_sso 1

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# Restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# UPGRADE DEPENDENCIES
#=================================================

ynh_install_app_dependencies biboumi

#=================================================
# SPECIFIC UPGRADE
#=================================================
# CONFIGURE BIBOUMI
#=================================================

biboumi_config_file="/etc/biboumi/biboumi.cfg"

# Verify the checksum of a file, stored by `ynh_store_file_checksum` in the install script.
ynh_backup_if_checksum_is_different "$biboumi_config_file"

# Get shared_secret from the config file
shared_secret="$(grep password "$biboumi_config_file" | cut -d= -f2)"

# Biboumi needs at least one admin JID.
admin_jid="${admin}@biboumi.${domain}"

# Create the biboumi config file.
cp ../conf/biboumi.cfg /etc/biboumi/
ynh_replace_string __DOMAIN__ "${domain}" "$biboumi_config_file"
ynh_replace_string __SECRET__ "${shared_secret}" "$biboumi_config_file"
ynh_replace_string __PORT__ "${port}" "$biboumi_config_file"
ynh_replace_string __ADMIN_JID__ "${admin_jid}" "$biboumi_config_file"

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$biboumi_config_file"

#=================================================
# UPGRADE METRONOME COMPONENT
#=================================================

# Upgrade metronome component
cp ../conf/biboumi.cfg.lua /etc/metronome/conf.d/
ynh_replace_string __DOMAIN__ "${domain}" /etc/metronome/conf.d/biboumi.cfg.lua
ynh_replace_string __SECRET__ "${shared_secret}" /etc/metronome/conf.d/biboumi.cfg.lua

#=================================================
# SETUP LOGROTATE
#=================================================

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate /var/log/biboumi/ --non-append

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions on app files
chown _biboumi /var/log/biboumi /var/lib/biboumi /etc/biboumi

#=================================================
# RELOAD SERVICES
#=================================================

ynh_systemd_action --action=restart --service_name=metronome
ynh_systemd_action --action=restart --service_name=biboumi
