#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
admin=$(ynh_app_setting_get --app=$app --key=admin)
port=$(ynh_app_setting_get --app=$app --key=port)

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# Prevent conflict with other apps on the same domain
ynh_app_setting_set --app=$app --key=no_sso --value=1

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# Restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression --message="Upgrading dependencies..." --weight=9

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# SPECIFIC UPGRADE
#=================================================
# CONFIGURE BIBOUMI
#=================================================

biboumi_config_file="/etc/biboumi/biboumi.cfg"
# Get shared_secret from the config file
secret="$(grep password "$biboumi_config_file" | cut -d= -f2)"
# Biboumi needs at least one admin JID.
admin_jid="${admin}@biboumi.${domain}"

# Create the biboumi config file.
ynh_add_config --template="../conf/biboumi.cfg" --destination="/etc/biboumi/biboumi.cfg"

#=================================================
# UPGRADE METRONOME COMPONENT
#=================================================

# Upgrade metronome component
cp ../conf/biboumi.cfg.lua /etc/metronome/conf.d/
ynh_add_config --template="../conf/biboumi.cfg.lua" --destination="/etc/metronome/conf.d/biboumi.cfg.lua"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Upgrading logrotate configuration..." --weight=1

# Use logrotate to manage app-specific logfile(s)
ynh_use_logrotate /var/log/biboumi/ --non-append

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions on app files
chown _biboumi /var/log/biboumi /var/lib/biboumi /etc/biboumi

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add biboumi --description="XMPP gateway for the IRC network" --log="/var/log/biboumi/biboumi.log"

#=================================================
# RELOAD SERVICES
#=================================================

ynh_systemd_action --action=restart --service_name=metronome
ynh_systemd_action --action=restart --service_name=biboumi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of Biboumi completed" --last
