#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# CREATE DIRECTORIES
#=================================================
ynh_script_progression "Setting up the data directory..."

# Set permissions to app files
chown -R _biboumi:_biboumi "/var/lib/$app"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

# Upgrade metronome component
metronome_config_dir=$(_get_metronome_config_dir)
ynh_config_add --template="metronome.cfg.lua" --destination="$metronome_config_dir/$app.cfg.lua"
chown metronome:metronome "$metronome_config_dir/$app.cfg.lua"
ynh_systemctl --service=metronome --action="restart"

# Upgrade biboumi configuration
ynh_config_add --template="biboumi.cfg" --destination="/etc/$app/$app.cfg"
chown -R _biboumi:_biboumi "/etc/$app/$app.cfg"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated systemd config
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="XMPP gateway for the IRC network" --log="/var/log/$app/$app.log"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R _biboumi:_biboumi "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Authenticated with the XMPP server"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
